[versions]
managed-nimbus-jose-jwt = "9.25.6"

micronaut = "3.7.5"
micronaut-docs = "2.0.0"
micronaut-test = "3.7.0"
groovy = "3.0.13"
spock = "2.1-groovy-3.0"

geb = "4.1"
reactor-test = "3.5.1"
selenium = "3.141.59"
serde = "1.0.1"
testcontainers = "1.17.6"
unboundid-ldapsdk = "6.0.6"
velocity-engine-core = "2.3"
bouncycastle = "1.70"
javax-activation = "1.2.0"
kotlin = "1.7.10"
bcpkix = "1.70"

[libraries]
managed-nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "managed-nimbus-jose-jwt" }

geb-spock = { module = "org.gebish:geb-spock", version.ref = "geb" }
groovy-json = { module = "org.codehaus.groovy:groovy-json", version.ref = "groovy" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
reactor-core = { module = "io.projectreactor:reactor-core" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactor-test" }
selenium-api = { module = "org.seleniumhq.selenium:selenium-api", version.ref = "selenium" }
selenium-chrome-driver = { module = "org.seleniumhq.selenium:selenium-chrome-driver", version.ref = "selenium" }
selenium-firefox-driver = { module = "org.seleniumhq.selenium:selenium-firefox-driver", version.ref = "selenium" }
selenium-remote-driver = { module = "org.seleniumhq.selenium:selenium-remote-driver", version.ref = "selenium" }
selenium-support = { module = "org.seleniumhq.selenium:selenium-support", version.ref = "selenium" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-selenium = { module = "org.testcontainers:selenium" }
unboundid-ldapsdk = { module = "com.unboundid:unboundid-ldapsdk", version.ref = "unboundid-ldapsdk" }
velocity-engine-core = { module = "org.apache.velocity:velocity-engine-core", version.ref = "velocity-engine-core" }
bcpkix-jdk15on = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncycastle" }
bcprov-jdk15on = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle" }
javax-activation = { module = "com.sun.activation:javax.activation", version.ref = "javax-activation" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
bcpkix = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bcpkix" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
